[package]
name = "test_dapp"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[addresses]
test_dapp = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-cli-v7.12.1" }
AptosStdlib   = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib",   rev = "aptos-cli-v7.12.1" }
MoveStdlib    = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib",    rev = "aptos-cli-v7.12.1" }

[dev-dependencies]
